### ISSUE TITLE
Documize patroni replica failed to restart

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#115]

**Comment by ShellyXueHan** [comment]
same error message from before, but should be something else that caused this:
```
2020-01-20 22:46:20,118 ERROR: watch
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 535, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 298, in _error_catcher
    yield
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 590, in read_chunked
    self._update_chunk_length()
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 539, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/patroni/dcs/kubernetes.py", line 421, in watch
    _request_timeout=(1, timeout + 1)):
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/watch/watch.py", line 130, in stream
    for line in iter_resp_lines(resp):
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/watch/watch.py", line 45, in iter_resp_lines
    for seg in resp.read_chunked(decode_content=False):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 618, in read_chunked
    self._original_response.close()
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 316, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

DB expert jumpping in + Cailey

**Comment by caggles** [comment]
Looks like the bottom error is the more relevant one - connection broken is a common issue when there are network interruptions. Seems likely that there was a problem getting the patroni pods to communicate. For now, I recommend monitoring the documize patroni pods to see if this is a recurring issue or just a one-off network issue.
