### ISSUE TITLE
Documize Patroni member won't start.

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#120]
```
2020-01-23 17:03:37,931 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc2cab15f28>, 'Connection to 172.50.0.1 timed out. (connect timeout=1)')': /api/v1/namespaces/hmg6pw-prod/pods?labelSelector=cluster-name%3Ddocumize-patroni-prod%2Capp.kubernetes.io%2Fname%3Dpatroni
2020-01-23 17:03:37,931 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc2cab15f28>, 'Connection to 172.50.0.1 timed out. (connect timeout=1)')': /api/v1/namespaces/hmg6pw-prod/pods?labelSelector=cluster-name%3Ddocumize-patroni-prod%2Capp.kubernetes.io%2Fname%3Dpatroni
2020-01-23 17:03:38,932 ERROR: get_cluster
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 138, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 98, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 88, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 350, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 837, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 281, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 143, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc2cab1c860>, 'Connection to 172.50.0.1 timed out. (connect timeout=1)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/patroni/utils.py", line 254, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/patroni/dcs/kubernetes.py", line 50, in wrapper
    return getattr(self._api, func)(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/client/apis/core_v1_api.py", line 12310, in list_namespaced_pod
    (data) = self.list_namespaced_pod_with_http_info(namespace, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/client/apis/core_v1_api.py", line 12413, in list_namespaced_pod_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/client/rest.py", line 205, in request
    headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 66, in request
    **urlopen_kw)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 671, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 671, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 671, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 363, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='172.50.0.1', port=443): Max retries exceeded with url: /api/v1/namespaces/hmg6pw-prod/pods?labelSelector=cluster-name%3Ddocumize-patroni-prod%2Capp.kubernetes.io%2Fname%3Dpatroni (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc2cab1c860>, 'Connection to 172.50.0.1 timed out. (connect timeout=1)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/patroni/dcs/kubernetes.py", line 141, in _load_cluster
    response = self.retry(self._api.list_namespaced_pod, self._namespace, label_selector=self._label_selector)
  File "/usr/local/lib/python3.5/dist-packages/patroni/dcs/kubernetes.py", line 113, in retry
    return self._retry.copy()(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/patroni/utils.py", line 263, in __call__
    raise RetryFailedError("Exceeded retry deadline")
patroni.utils.RetryFailedError: 'Exceeded retry deadline'
2020-01-23 17:03:38,934 ERROR: Error communicating with DCS
2020-01-23 17:03:38,936 WARNING: Loop time exceeded, rescheduling immediately.
```

@ShellyXueHan has tried restarting the pod, scaling down and up again, and trying to rebuild the member on a fresh PVC. Nothing seems to work. We may have to dump and create a fresh database for import.

Further investigation is necessary.

**Comment by caggles** [comment]
@ShellyXueHan the pod is back up again - did you do anything to it?

**Comment by ShellyXueHan** [comment]
the pod is not killed yet but still getting issues:

2020-01-28 11:26:41,202 WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='172.50.0.1', port=443): Read timed out. (read timeout=1)",)': /api/v1/namespaces/hmg6pw-prod/pods?labelSelector=cluster-name%3Ddocumize-patroni-prod%2Capp.kubernetes.io%2Fname%3Dpatroni

and a bunch of query errors.

**Comment by ShellyXueHan** [comment]
Update:
Encounter the same issue during upgrade. Issue started with connection issue then after several time turn into too many retry. There's wired issue in the statefulset setup, e.g. missing volume binding, privilege issue...

I've delete the original statefulset. Updated dc and created new one when db restore. Tested on killing pod and restarting, have no problem now.
